GET http://localhost:8080/hello

###
POST http://localhost:8080/responseBody

A text example

###
POST http://localhost:8080/requestBody
Content-Type: application/json

{
  "id": 3,
  "name": "Something"
}